-- ============================================================================
-- FlyGuru — Этап 4: админка. Одна миграция на весь этап (подэтапы 4.0–4.10).
-- Накатить через Supabase SQL Editor. Идемпотентно.
--
-- Содержимое:
--   1. Номер заявки (виден клиенту и админу).
--   2. Отметка переноса записи (перенос = смена даты, статус живёт).
--   3. Лог ручных корректировок минут абонемента (кто, сколько, почему).
--   4. Одноразовые инвайт-токены для регистрации членов клуба.
-- ============================================================================

-- ── 1. Номер заявки ──────────────────────────────────────────────────────────
-- Человеческий номер (#1042) вместо uuid: клиент видит его на /thanks,
-- админ — в ленте. identity сам нумерует и старые, и новые строки
-- (существующие получат номера в произвольном порядке — их единицы, не страшно).
alter table bookings
  add column if not exists booking_no integer generated by default as identity;

create unique index if not exists bookings_booking_no_key on bookings (booking_no);

-- ── 2. Перенос записи ────────────────────────────────────────────────────────
-- «Перенесена» — не конечный статус (клиент всё ещё придёт!): админ меняет
-- дату, заявка остаётся в confirmed, а отметка даёт бейдж «перенесена» в ленте.
alter table bookings
  add column if not exists rescheduled_at timestamptz;

-- ── 3. Лог корректировок минут абонемента ────────────────────────────────────
-- Ручная правка остатка (компенсация, бонус, ошибка при списании) — только
-- с комментарием. Остаток теперь считается как:
--   total_minutes + сумма(delta_minutes) − сумма(sessions.minutes_used).
create table if not exists subscription_adjustments (
  id              uuid primary key default gen_random_uuid(),
  subscription_id uuid not null references subscriptions(id) on delete cascade,
  delta_minutes   integer not null check (delta_minutes <> 0),
  comment         text not null check (length(trim(comment)) > 0),
  created_by      uuid references users(id) on delete set null,
  created_at      timestamptz not null default now()
);

create index if not exists subscription_adjustments_subscription_idx
  on subscription_adjustments (subscription_id);

alter table subscription_adjustments enable row level security;

-- Читает весь персонал: без корректировок инструктор неправильно посчитает
-- остаток минут при списании.
create policy sub_adjustments_select_staff on subscription_adjustments
  for select to authenticated
  using (app_role() in ('instructor', 'admin'));

-- Правят абонементы и админ, и инструктор (решение владельца) — но запись
-- в логе всегда от своего имени.
create policy sub_adjustments_insert_staff on subscription_adjustments
  for insert to authenticated
  with check (
    app_role() in ('instructor', 'admin')
    and created_by = app_user_id()
  );

create policy sub_adjustments_admin_all on subscription_adjustments
  for all to authenticated
  using (app_role() = 'admin') with check (app_role() = 'admin');

-- ── 4. Инвайт-токены членов клуба ────────────────────────────────────────────
-- Админ создаёт клиента-члена клуба и генерит одноразовую ссылку
-- /invite/<token>; клиент по ней ставит пароль — появляется auth-аккаунт
-- с ролью member, привязанный к клиенту. Токен живёт 7 дней, одноразовый.
create table if not exists invite_tokens (
  id         uuid primary key default gen_random_uuid(),
  token      text not null unique,
  client_id  uuid not null references clients(id) on delete cascade,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '7 days'),
  used_at    timestamptz
);

alter table invite_tokens enable row level security;

-- Страница /invite/[token] анонимная и ходит через service_role (мимо RLS);
-- политика нужна только админу — видеть и создавать ссылки из кабинета.
create policy invite_tokens_admin_all on invite_tokens
  for all to authenticated
  using (app_role() = 'admin') with check (app_role() = 'admin');
